// <auto-generated />
namespace Filmes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AlterFilmeInAvaliacaoToFloat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterFilmeInAvaliacaoToFloat));
        
        string IMigrationMetadata.Id
        {
            get { return "202412061845288_AlterFilmeInAvaliacaoToFloat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
